### PR TITLE
I've made new branch, and added #DevOps CI/CD to make an awesome website for you...

### PR DESCRIPTION
**Pull request by verbose9**

### CODE REVIEW

**Comment by PhyX-Meow** [comment]
Oh god, thanks, but I don't need this, this repo is just used to sync settings between my pc and laptop.
qwq

**Comment by PhyX-Meow** [comment]
And actually I have no knowledge abort js and website building.....

**Comment by verbose9** [comment]
> And actually I have no knowledge abort js and website building.....

😊 no problem

**Comment by verbose9** [comment]
closing

**Pull request closed without merging**
